name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo 'export PATH="$HOME/.bun/bin:$PATH"' >> $GITHUB_ENV
        shell: bash

      # Verify Bun installation
      - name: Verify Bun
        run: bun --version

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Run Biome lint
      - name: Run Biome lint
        run: bun run lint:biome