name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Check Bun files
        run: ls -la $HOME/.bun/bin

      - name: Verify Bun installation
        run: bun --version

      - name: Install dependencies
        run: bun install

      - name: Run Biome lint
        run: bun run lint:biome
